# Generated by Django 4.0.5 on 2022-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0002_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
